### ISSUE TITLE
Describe the zarr file format in the documentation

### ISSUE THREAD

**Issue by shoyer** [alimanfoo/zarr#5]
It looks like the design is very similar to `bcolz`, but this would be nice to have as a point of reference.

**Comment by alimanfoo** [comment]
Yep, good idea. 

FWIW I basically copied bcolz but made a couple of changes. 

(1) I dropped the bloscpack header from the chunk data files, because it's not needed and I was trying to strip everything down to bare essentials. So each chunk data file contains the compressed data that c-blosc returns and nothing else.

(2) I used pickle instead of JSON for the metadata because it was simpler and easier to guarantee correct round-trip to/from Python objects. However I'd be happy to consider changing to JSON if it would help.

All details of the storage format are open to discussion.

**Comment by alimanfoo** [comment]
Some documentation like this would be good: https://github.com/Blosc/bcolz/blob/master/DISK_FORMAT_v1.rst
